version: '2'
services:
    npm:
        image: node:6
        env_file: .env
        entrypoint: npm
        command: run start:dev
        working_dir: /app
        ports:
            - "$PORT:$PORT"
        volumes:    
            - .:/app
        links:
            - redis
            - postgres
    redis:
        image: redis:3
        ports:
          - "6379:6379"
        logging:
            driver: none
    postgres:
        image: postgres:9.6
        ports:
            - "5432:5432"
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
